import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowDown, ArrowDownRight, ArrowUpRight, BadgeCheck, BriefcaseBusiness, CalendarDays, Code2, Download, ExternalLink, GraduationCap, Layers3, Mail, MapPin, Menu, MessageCircle, MoveUpRight, Phone, Send, Sparkles, X, Zap } from "lucide-react";
import "../css/portfolio.css";

const navItems = [["Home", "home"], ["About", "about"], ["Skills", "skills"], ["Projects", "projects"], ["Education", "education"], ["Experience", "experience"], ["Contact", "contact"]];
const skillGroups = [
  { title: "Development", icon: Code2, items: [["HTML5", "Advanced"], ["CSS3", "Advanced"], ["JavaScript", "Intermediate"], ["React", "Learning"], ["Java", "Intermediate"], ["Python", "Intermediate"], ["SQL", "Intermediate"], ["Bootstrap", "Advanced"]] },
  { title: "Tools & workflow", icon: Layers3, items: [["Git", "Intermediate"], ["GitHub", "Intermediate"], ["VS Code", "Advanced"], ["Figma", "Learning"], ["Responsive Design", "Desktop • Tablet • Mobile"], ["Cloud Basics", "Learning Cloud Technologies"]] },
];
const businessSkills = ["Business Management", "Digital Marketing", "HR Management", "Sales", "SEO", "Business Analytics"];
const professionalSkills = ["Communication", "Teamwork", "Problem Solving", "Time Management", "Leadership", "Continuous Learning", "Technical Support", "Customer Support", "Troubleshooting", "System Support", "Networking Basics"];
const interests = ["Web Development", "Frontend Development", "Software Development", "Java Programming", "Python Programming", "Business Management", "Digital Marketing", "HR Management", "Sales", "Technical Support", "Business Analytics", "UI / UX Design", "Cloud Computing", "Artificial Intelligence"];
const certificates = [["Programming in Java", "NPTEL"], ["Introduction to Database Management System", "NPTEL"], ["Cloud Computing", "NPTEL"], ["Python Fundamentals", "Programming & Problem Solving"], ["Python for Machine Learning", "Machine Learning Basics"], ["R Programming", "Data Analytics"], ["Digital Marketing", "Marketing Fundamentals"]];
const projects = [
  { title: "WorkSphere", type: "AI analytics platform", image: "/images/worksphere.svg", description: "Built an AI-powered employee performance and analytics platform to help teams understand performance and make informed decisions.", stack: ["JavaScript", "Node.js", "AI"], live: "https://worksphere-kohl.vercel.app/", github: "https://github.com/pradeep312205/WorkSphere", number: "01" },
  { title: "SolarGuard AI", type: "Machine learning project", image: "/images/solarguard-ai.svg", description: "Created a solar energy forecasting and technician maintenance assistant using machine learning and Flask.", stack: ["Python", "Flask", "Machine Learning"], live: "https://solarguard-ai-dab1.onrender.com/", github: "https://github.com/pradeep312205/SolarGuard-AI", number: "02" },
  { title: "BizNovexa Symposium Website", type: "College project", image: "/images/biznovexa.png", description: "Designed and developed the official website for BizNovexa, showcasing symposium events, registration details, schedules, and event information with a modern responsive interface.", stack: ["HTML5", "CSS3", "JavaScript", "Vercel"], live: "https://rit-biz-novexa-2026.vercel.app/", github: "https://github.com/pradeep312205", number: "03" },
  { title: "Al Jodha Technical Services", type: "Client website", image: "/images/aljodha.png", description: "Designed and developed a professional business website for Al Jodha Technical Services, including services, project highlights, contact details, and a responsive user interface.", stack: ["HTML5", "CSS3", "JavaScript", "Bootstrap"], live: "https://www.aljodha.com", github: "https://github.com/pradeep312205", number: "04" },
  { title: "Nexcent Landing Page", type: "Frontend project", image: "/images/nexcent.png", description: "Designed and developed a modern, fully responsive landing page for Nexcent using HTML, CSS, and JavaScript, with reusable sections and layouts for desktop, tablet, and mobile.", stack: ["HTML5", "CSS3", "JavaScript"], live: "https://pradeep312205.github.io/nexcent/", github: "https://github.com/pradeep312205", number: "05" },
  { title: "Personal Portfolio", type: "Portfolio website", image: "/images/portfolio.png", description: "Built a responsive personal portfolio to showcase projects, education, skills, certifications, internships, and achievements using modern frontend technologies.", stack: ["React", "CSS", "Framer Motion"], live: "https://kp-portfolio-seven.vercel.app/", github: "https://github.com/pradeep312205/kp-portfolio", number: "06" },
  { title: "Taxi Booking System", type: "Java desktop project", image: "/images/taxi.png", description: "Developed a Taxi Booking System using Java and object-oriented programming. The application manages taxi bookings, customer information, fare calculations, and booking history.", stack: ["Java", "OOP", "Collections"], live: "", github: "https://github.com/pradeep312205", number: "07" },
];
const education = [
  { year: "2023 — 2027", title: "Bachelor of Technology", field: "Computer Science and Business Systems", institution: "Ramco Institute of Technology", place: "Rajapalayam", detail: "Pursuing a bachelor's degree with a focus on web development, Java programming, database management, and software engineering.", score: "CGPA · 7.12" },
  { year: "2022 — 2023", title: "Higher Secondary Education", field: "Computer Science", institution: "K.R.A. Vidyashram Higher Secondary School", place: "Kovilpatti", detail: "Completed Higher Secondary Education with Mathematics and Computer Science, building a strong foundation in programming and analytical thinking.", score: "Percentage · 70%" },
];
const experience = [
  ["Frontend Developer Intern", "Icanio Technologies", "Tirunelveli", "Developed responsive websites using HTML, CSS, JavaScript and worked on real-world frontend projects."],
  ["Cyber Security Intern", "Supraja Technologies", "Hyderabad", "Learned cybersecurity fundamentals, vulnerability assessment and security best practices."],
  ["Freelance Web Developer", "Al Jodha Technical Services", "Client Project", "Designed and developed a responsive company website with modern UI."],
  ["Digital Marketing Freelancer", "Freelance", "Remote", "Worked on social media, branding and digital marketing campaigns."],
  ["Technical Support", "Dubai Client", "Remote", "Provided technical support, website maintenance and client assistance."],
  ["SEO Optimizer", "Cool Care Center", "Kovilpatti", "Improved website ranking using SEO techniques and keyword optimization."],
  ["Web Developer", "Biznovexa Symposium", "Ramco Institute of Technology", "Designed and developed the official symposium website for Biznovexa 2026."],
  ["Poster Designer", "College Events", "Freelance / Academic", "Designed posters, banners and digital creatives using Canva."],
];
const services = [["Web Development", "Responsive, modern websites built with HTML, CSS, JavaScript and React."], ["Software Development", "Software solutions using Java, Python and problem-solving techniques."], ["Digital Marketing", "Campaigns, SEO, content promotion and stronger online presence."], ["Business Management", "Planning, teamwork, decision-making and organizational growth."], ["HR Management", "Recruitment support, employee coordination and clear communication."], ["Technical Support", "Troubleshooting and practical help for users and software issues."]];
const courseWork = ["Programming · Java, Python, C Programming", "Database · DBMS & SQL", "Web Development · HTML, CSS, JavaScript, Bootstrap", "Computer Networks · Networking Fundamentals", "Data Structures · Algorithms & Problem Solving", "Business Analytics · Analytics & Business Systems"];

function Reveal({ children, className = "", delay = 0 }) {
  const reduceMotion = useReducedMotion();
  return <motion.div className={className} initial={reduceMotion ? false : { opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.12 }} transition={{ duration: reduceMotion ? 0 : 0.6, delay, ease: [0.2, 0.8, 0.2, 1] }}>{children}</motion.div>;
}
function TiltCard({ children, className = "" }) { const reduceMotion = useReducedMotion(); return <motion.div className={className} style={{ transformStyle: "preserve-3d" }} whileHover={reduceMotion ? undefined : { rotateX: -2, rotateY: 2, y: -5 }} transition={{ type: "spring", stiffness: 190, damping: 20 }}>{children}</motion.div>; }
function Eyebrow({ children, icon: Icon = Sparkles }) { return <div className="eyebrow"><Icon size={14} strokeWidth={1.8} /><span>{children}</span></div>; }
function SectionTitle({ kicker, title, body, number }) { return <Reveal className="section-heading"><div className="section-heading-top"><Eyebrow>{kicker}</Eyebrow><span className="section-number">{number}</span></div><h2>{title}</h2>{body && <p>{body}</p>}</Reveal>; }

function Header({ active, setActive }) {
  const [open, setOpen] = useState(false);
  useEffect(() => {
    const sections = navItems.map(([, id]) => document.getElementById(id)).filter(Boolean);
    const observer = new IntersectionObserver((entries) => { const visible = entries.filter((entry) => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0]; if (visible) setActive(visible.target.id); }, { rootMargin: "-22% 0px -58% 0px", threshold: [0, 0.1, 0.25] });
    sections.forEach((section) => observer.observe(section)); return () => observer.disconnect();
  }, [setActive]);
  const close = (id) => { setOpen(false); setActive(id); };
  return <header className="site-header"><nav className="nav-shell" aria-label="Main navigation"><a className="brand" href="#home" onClick={() => close("home")}><span className="brand-mark">P<span>.</span></span><span>Pradeep<span className="brand-caption">PORTFOLIO / 2026</span></span></a>
    <button className="menu-toggle" aria-label={open ? "Close navigation" : "Open navigation"} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button>
    <div className={`nav-content ${open ? "is-open" : ""}`}><div className="nav-links">{navItems.map(([label, id]) => <a key={id} href={`#${id}`} className={active === id ? "active" : ""} onClick={() => close(id)}>{label}</a>)}</div><a className="nav-contact" href="#contact" onClick={() => close("contact")}>Let’s talk <ArrowUpRight size={15} /></a></div>
  </nav></header>;
}

function Hero() {
  const reduceMotion = useReducedMotion();
  return <section className="hero section-wrap" id="home"><div className="hero-grid-art" aria-hidden="true" /><div className="hero-copy"><Reveal><Eyebrow icon={Zap}>AVAILABLE FOR OPPORTUNITIES <span className="status-dot" /></Eyebrow><h1>Ideas into<br /><span className="hero-italic">impact.</span></h1><p className="hero-intro">I’m <strong>Pradeep</strong> — I build modern, responsive and user-friendly websites with HTML, CSS and JavaScript, bringing technology and business together.</p><div className="hero-actions"><a className="button button-primary" href="#projects">Explore my work <ArrowUpRight size={17} /></a><a className="button button-quiet" href="/assets/resume.pdf" target="_blank" rel="noreferrer"><Download size={16} /> Download CV</a></div></Reveal><Reveal delay={0.18} className="hero-foot"><span><MapPin size={15} /> Kovilpatti, Tamil Nadu</span><span>CSBS · Ramco Institute of Technology</span></Reveal></div>
    <Reveal className="hero-visual" delay={0.15}><div className="portrait-stage"><div className="portrait-halo" /><TiltCard className="portrait-frame"><img src="/images/profile.jpeg" alt="Portrait of Pradeep" /><span className="portrait-index">01 / CREATIVE DEVELOPER</span></TiltCard><motion.div className="float-card float-card-top" animate={reduceMotion ? undefined : { y: [0, -9, 0], rotate: [2, 0, 2] }} transition={{ duration: 5, repeat: Infinity, ease: "easeInOut" }}><Code2 size={16} /><span>Building for<br /><b>the web</b></span></motion.div><motion.div className="float-card float-card-bottom" animate={reduceMotion ? undefined : { y: [0, 8, 0], rotate: [-2, 0, -2] }} transition={{ duration: 6, repeat: Infinity, ease: "easeInOut" }}><span className="float-spark"><Sparkles size={16} /></span><span>Tech with a<br /><b>human touch</b></span></motion.div><div className="orbit orbit-one" /><div className="orbit orbit-two" /></div></Reveal>
    <a className="scroll-cue" href="#about"><span>SCROLL TO EXPLORE</span><ArrowDown size={14} /></a></section>;
}

function About() {
  return <section id="about" className="section-wrap section-block about-section"><SectionTitle number="01" kicker="A LITTLE ABOUT ME" title={<>Curious by nature.<br /><em>Builder by choice.</em></>} body="I am a Computer Science and Business Systems student passionate about building modern websites, learning new technologies and solving real-world problems through software." />
    <div className="about-layout"><Reveal className="about-note"><span className="quote-mark">“</span><p>I enjoy creating clean, responsive and user-friendly websites. Alongside web development, I have experience in software development, digital marketing, SEO and business management. I continuously improve my technical skills by building projects and learning modern technologies.</p><div className="signature">Pradeep <span>↗</span></div></Reveal><div className="service-grid">{services.map(([service, detail], i) => <Reveal key={service} delay={i * 0.04}><div className="service-item"><span className="service-no">0{i + 1}</span><div><h3>{service}</h3><p>{detail}</p></div><ArrowUpRight size={16} /></div></Reveal>)}</div></div>
    <Reveal className="journey-strip"><div><Eyebrow icon={CalendarDays}>MY JOURNEY</Eyebrow><p>My learning and project journey through Computer Science and Business Systems.</p></div><div className="journey-years">{[["2023", "Started my B.Tech in Computer Science and Business Systems."], ["2024", "Built my first responsive websites using HTML, CSS and JavaScript."], ["2025", "Completed internships and worked on frontend development projects."], ["2026", "Building advanced portfolio projects and preparing for software careers."], ["2027", "Completed my Bachelor of Technology in Computer Science and Business Systems from Ramco Institute of Technology."]].map(([year, detail], i) => <div key={year} className="journey-year"><span>{year}</span><i className={i === 3 ? "current" : ""} /><small>{detail}</small></div>)}</div></Reveal></section>;
}

function SkillMeter({ title, icon: Icon, items }) {
  return <TiltCard className="skill-panel"><div className="skill-panel-title"><span className="icon-box"><Icon size={18} /></span><h3>{title}</h3><ArrowUpRight size={16} /></div><div className="skill-list">{items.map(([name, level], i) => <div className="skill-line" key={name}><div className="skill-label"><span>{name}</span><span className="skill-level">{level}</span></div><div className="skill-track"><motion.span initial={{ scaleX: 0 }} whileInView={{ scaleX: ["Advanced", "Intermediate"].includes(level) ? 0.82 : 0.52 }} viewport={{ once: true }} transition={{ duration: 0.75, delay: i * 0.07 }} style={{ transformOrigin: "left" }} /></div></div>)}</div></TiltCard>;
}
function Skills() {
  return <section id="skills" className="section-wrap section-block skills-section"><SectionTitle number="02" kicker="MY EXPERTISE" title={<>A versatile toolkit<br /><em>for meaningful work.</em></>} body="I continuously improve my technical, business and professional skills through academic projects, internships, certifications and self-learning." />
    <div className="skills-layout"><div className="skill-panels">{skillGroups.map((group, i) => <Reveal key={group.title} delay={i * 0.1}><SkillMeter {...group} /></Reveal>)}</div><Reveal className="business-panel"><Eyebrow icon={BriefcaseBusiness}>BEYOND THE CODE</Eyebrow><h3>Business &<br /><em>professional</em><br />skills.</h3><p>Skills developed through my Computer Science and Business Systems curriculum.</p><div className="tag-cloud">{[...businessSkills, ...professionalSkills].map((s) => <span key={s}>{s}</span>)}</div></Reveal></div>
    <Reveal className="skills-lower"><div className="interest-row"><div><span className="interest-title">AREAS OF INTEREST</span><p>{interests.join("  ·  ")}</p></div><ArrowDownRight size={19} /></div><div className="cert-row"><div><Eyebrow icon={BadgeCheck}>CERTIFICATIONS & COURSES</Eyebrow><p>Professional certifications and courses completed to strengthen my technical and business knowledge.</p></div><div className="cert-list">{certificates.map(([course, issuer]) => <div className="cert-item" key={course}><span><b>{course}</b><small>{issuer}</small></span><ArrowUpRight size={15} /></div>)}</div></div></Reveal></section>;
}

function ProjectCard({ project, index }) {
  return <Reveal delay={index % 2 ? 0.08 : 0}><motion.article className={`project-card ${index % 2 ? "project-card-offset" : ""}`} whileHover={{ y: -5 }} transition={{ duration: 0.25 }}><a className="project-image" href={project.live || project.github} target="_blank" rel="noreferrer"><img src={project.image} alt={`${project.title} project preview`} loading="lazy" /><span className="image-open"><ArrowUpRight size={19} /></span><span className="image-number">{project.number}</span></a><div className="project-meta"><span>{project.type}</span><span>{project.stack.slice(0, 2).join(" · ")}</span></div><h3>{project.title}</h3><p>{project.description}</p><div className="project-tags">{project.stack.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="project-links">{project.live && <a href={project.live} target="_blank" rel="noreferrer">Live project <ExternalLink size={14} /></a>}<a href={project.github} target="_blank" rel="noreferrer">Source code <Code2 size={14} /></a></div></motion.article></Reveal>;
}
function Projects() {
  return <section id="projects" className="section-wrap section-block projects-section"><div className="project-heading-row"><SectionTitle number="03" kicker="SELECTED WORK" title={<>Made with intent.<br /><em>Built to be useful.</em></>} body="Projects that reflect my technical knowledge, creativity and practical problem-solving skills." /><a className="text-link" href="https://github.com/pradeep312205" target="_blank" rel="noreferrer">More on GitHub <ArrowUpRight size={16} /></a></div><div className="project-grid">{projects.map((project, i) => <ProjectCard key={project.title} project={project} index={i} />)}</div><Reveal className="project-details-band"><div className="project-stat-grid">{[["2+", "Major Projects"], ["10+", "Technologies Used"], ["5000+", "Lines of Code"], ["300+", "Development Hours"]].map(([value, label]) => <div key={label}><b>{value}</b><span>{label}</span></div>)}</div><div className="project-process"><Eyebrow icon={Layers3}>DEVELOPMENT PROCESS</Eyebrow><div>{[["01", "Planning", "Gathered requirements, identified user needs, and planned the project architecture."], ["02", "Design", "Created responsive layouts with modern UI and user-friendly navigation."], ["03", "Development", "Implemented clean, maintainable code using modern web technologies and Java."], ["04", "Testing", "Tested functionality, responsiveness, and fixed bugs before deployment."]].map(([number, title, detail]) => <div key={title}><span>{number}</span><b>{title}</b><small>{detail}</small></div>)}</div></div></Reveal><Reveal className="project-cta"><div><Eyebrow icon={Zap}>OPEN TO OPPORTUNITIES</Eyebrow><h3>Interested in working together?</h3><p>I'm currently looking for Web Development, Software Development, and Front-End Development opportunities.</p></div><a className="button button-primary" href="#contact">Let’s talk <ArrowUpRight size={16} /></a></Reveal></section>;
}

function Education() {
  return <section id="education" className="section-wrap section-block education-section"><SectionTitle number="04" kicker="ACADEMIC JOURNEY" title={<>Learning with<br /><em>every new chapter.</em></>} body="Building knowledge through academics, certifications, technical skills and continuous learning." /><div className="education-layout"><div className="education-list">{education.map((item, i) => <Reveal key={item.title} delay={i * 0.1}><TiltCard className="education-card"><div className="education-icon"><GraduationCap size={19} /></div><div className="education-copy"><span className="education-year">{item.year}</span><h3>{item.title}</h3><h4>{item.field}</h4><p className="education-institution">{item.institution} <span>· {item.place}</span></p><p>{item.detail}</p><span className="education-score">{item.score}</span></div></TiltCard></Reveal>)}</div><Reveal className="course-panel"><Eyebrow icon={Layers3}>RELEVANT COURSEWORK</Eyebrow><div className="course-list">{courseWork.map((item, i) => <div className="course-item" key={item}><span>0{i + 1}</span><p>{item}</p></div>)}</div></Reveal></div>
    <Reveal className="achievement-band"><div><Eyebrow icon={BadgeCheck}>MILESTONES</Eyebrow><p>Solved 250+ Programming Problems. Developed Multiple Responsive Websites. Completed Several Technical Certifications. Participated in Web Development Projects. Built Real-Time Frontend Applications.</p></div><div className="achievement-mark">250<span>+</span><small>PROBLEMS SOLVED</small></div></Reveal><Reveal className="objective-card"><span className="objective-mark">“</span><div><Eyebrow>CAREER OBJECTIVE</Eyebrow><p>To begin my career as a Frontend/Web Developer where I can apply my technical knowledge, creativity, and problem-solving skills while continuously learning modern technologies and contributing to innovative projects.</p></div></Reveal></section>;
}

function Experience() {
  const gains = [["Frontend Development", "HTML5, CSS3, JavaScript, Responsive Web Design"], ["UI / UX Design", "Modern layouts, responsive interfaces and user experience."], ["SEO", "On-page SEO, keyword optimization and website visibility."], ["Digital Marketing", "Brand promotion, campaigns and social media marketing."], ["Technical Support", "Troubleshooting, website maintenance and client support."], ["Cyber Security", "Security awareness, vulnerability assessment and best practices."]];
  return <section id="experience" className="section-wrap section-block experience-section"><SectionTitle number="05" kicker="MY PROFESSIONAL JOURNEY" title={<>Learning through<br /><em>real-world work.</em></>} body="Building practical skills through internships, freelancing and real-world client projects." /><div className="experience-layout"><div className="experience-list">{experience.map(([role, org, place, desc], i) => <Reveal key={`${role}-${org}`} delay={Math.min(i * 0.04, 0.2)}><div className="experience-item"><span className="experience-dot" /><span className="experience-index">0{i + 1}</span><div><span className="experience-place">{org} · {place}</span><h3>{role}</h3><p>{desc}</p></div><ArrowUpRight className="experience-arrow" size={16} /></div></Reveal>)}</div><div className="experience-aside"><Reveal className="skills-gained"><Eyebrow icon={Sparkles}>SKILLS GAINED</Eyebrow><p>Skills acquired through internships, freelance work, and real-world client projects.</p><div>{gains.map(([title, detail]) => <div key={title} className="gain-item"><b>{title}</b><span>{detail}</span></div>)}</div></Reveal><Reveal className="experience-stats"><div><b>8<span>+</span></b><small>PROJECTS COMPLETED</small></div><div><b>3<span>+</span></b><small>INTERNSHIPS</small></div><div><b>5<span>+</span></b><small>CLIENT PROJECTS</small></div><div><b>250<span>+</span></b><small>PROBLEMS SOLVED</small></div></Reveal></div></div>
    <Reveal className="career-highlights"><Eyebrow icon={Sparkles}>CAREER HIGHLIGHTS</Eyebrow><div className="highlights-grid"><div><h3>8+ Projects</h3><p>Successfully completed multiple academic, freelance, and client projects.</p></div><div><h3>Frontend Development</h3><p>Built responsive websites using HTML, CSS, JavaScript, and Bootstrap.</p></div><div><h3>Professional Experience</h3><p>Worked with startups, businesses, and clients through internships and freelance work.</p></div></div></Reveal><Reveal className="objective-card"><span className="objective-mark">“</span><div><Eyebrow>CAREER OBJECTIVE</Eyebrow><p>I aim to build a successful career as a Full Stack Web Developer by continuously improving my technical expertise, learning modern technologies, and delivering high-quality software solutions that create real business value.</p></div></Reveal></section>;
}

function Contact() {
  const [status, setStatus] = useState(""); const [sending, setSending] = useState(false);
  async function handleSubmit(event) {
    event.preventDefault(); setSending(true); setStatus(""); const form = new FormData(event.currentTarget);
    const contactForm = event.currentTarget;
    try { const response = await fetch("https://kp-portfolio-backend.onrender.com/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), email: form.get("email"), subject: form.get("subject"), message: form.get("message") }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message || "Unable to send your message right now."); setStatus(payload.message || "Thanks — your message has been sent."); contactForm.reset(); }
    catch (error) { setStatus(error.message || "There was a problem sending your message. Please email me directly."); } finally { setSending(false); }
  }
  return <section id="contact" className="section-wrap section-block contact-section"><div className="contact-top"><SectionTitle number="06" kicker="GET IN TOUCH" title={<>Let’s make<br /><em>something matter.</em></>} body="I'm always open to internships, freelance projects, web development opportunities, and collaborations." /><Reveal className="contact-direct"><span>HAVE A PROJECT IN MIND?</span><a href="mailto:karthiklatha789@gmail.com">Let’s start a conversation <ArrowUpRight size={19} /></a></Reveal></div><div className="contact-layout"><Reveal className="contact-details"><div className="contact-detail"><span className="contact-icon"><Mail size={17} /></span><div><small>EMAIL</small><a href="mailto:karthiklatha789@gmail.com">karthiklatha789@gmail.com</a></div></div><div className="contact-detail"><span className="contact-icon"><Phone size={17} /></span><div><small>PHONE</small><a href="tel:+919345395524">+91 93453 95524</a></div></div><div className="contact-detail"><span className="contact-icon"><MapPin size={17} /></span><div><small>LOCATION</small><span>Kovilpatti, Tamil Nadu</span></div></div><div className="social-links"><a href="https://github.com/Pradeep312205" target="_blank" rel="noreferrer" aria-label="GitHub"><Code2 /></a><a href="https://www.linkedin.com/in/YOUR-LINKEDIN/" target="_blank" rel="noreferrer" aria-label="LinkedIn"><span className="social-letter">in</span></a><a href="https://www.instagram.com/YOUR_USERNAME/" target="_blank" rel="noreferrer" aria-label="Instagram"><span className="social-letter">◎</span></a><a href="mailto:karthiklatha789@gmail.com" aria-label="Email"><Mail /></a></div></Reveal><Reveal className="contact-form-wrap"><div className="form-heading"><Eyebrow icon={MessageCircle}>SEND A MESSAGE</Eyebrow><p>Have a question or an opportunity? Feel free to send me a message.</p></div><form className="contact-form" onSubmit={handleSubmit}><div className="form-row"><label>Your name<input name="name" autoComplete="name" placeholder="Jane Smith" required /></label><label>Email address<input type="email" name="email" autoComplete="email" placeholder="jane@email.com" required /></label></div><label>Subject<input name="subject" placeholder="What would you like to discuss?" required /></label><label>Your message<textarea name="message" rows="4" placeholder="A little about what you have in mind…" required /></label><div className="form-submit"><button className="button button-primary" disabled={sending}>{sending ? "Sending…" : "Send message"}<Send size={15} /></button><span>Usually reply within 1–2 business days.</span></div><p className="form-status" aria-live="polite">{status}</p></form></Reveal></div></section>;
}

function Footer() { return <footer className="site-footer"><div className="footer-main section-wrap"><a className="brand" href="#home"><span className="brand-mark">P<span>.</span></span><span>Pradeep<span className="brand-caption">DIGITAL EXPERIENCES WITH PURPOSE</span></span></a><p>Frontend Developer & Software Developer<br />Tamil Nadu, India</p><a className="back-top" href="#home">Back to top <MoveUpRight size={15} /></a></div><div className="footer-bottom section-wrap"><span>© 2026 Pradeep. All Rights Reserved.</span><span>Designed & built with <span className="footer-heart">♥</span> and intention.</span></div></footer>; }

function App() {
  const [active, setActive] = useState("home");
  useEffect(() => { const pathAnchors = { "about.html": "about", "skills.html": "skills", "projects.html": "projects", "education.html": "education", "experience.html": "experience", "contact.html": "contact" }; const file = window.location.pathname.split("/").pop(); const target = pathAnchors[file]; if (target) window.setTimeout(() => document.getElementById(target)?.scrollIntoView({ behavior: "smooth" }), 60); if (window.location.hash) window.setTimeout(() => document.querySelector(window.location.hash)?.scrollIntoView({ behavior: "smooth" }), 80); }, []);
  return <><div className="page-grain" aria-hidden="true" /><Header active={active} setActive={setActive} /><main><Hero /><About /><Skills /><Projects /><Education /><Experience /><Contact /></main><Footer /><a className="floating-contact" href="mailto:karthiklatha789@gmail.com" aria-label="Email Pradeep"><Mail size={17} /></a></>;
}
createRoot(document.getElementById("root")).render(<React.StrictMode><App /></React.StrictMode>);
